### ISSUE TITLE
Add rank tier / division ENUMs

### ISSUE THREAD

**Issue by johnsturgeon** [johnsturgeon/stat-scraper-web#2]
- [x] johnsturgeon/stat-scraper#1
- [x] johnsturgeon/stat-scraper-web#5
- [x] johnsturgeon/stat-scraper-web#6
